Updated readme
ssrando/ssrando pull request #118
Opened 2021-09-18 01:10 UTC by yannl35133

2021-09-20 10:07 UTC, lepelog requested changes

2021-09-20 10:07 UTC, lepelog commented on README.md
> +- Lepelog: Main developer
name is lowercase

2021-09-20 10:07 UTC, lepelog commented on README.md
> -### Changes
I agree with removing the flags from here, but they should be noted in some textfile in the randomizer, so we don't loose track of them. Maybe `README-dev.md`?

2021-09-20 11:30 UTC, yannl35133 commented on README.md
> +    `/wbfs/The Legend of Zelda Skyward Sword [SOUE01]/`
I just kept what was originally written, and it is also my folder structure for WiiFlow

2021-09-20 11:40 UTC, yannl35133 commented on README.md
> +3. Choose the branch you want to run (`gui-redesign` is the most up-to-date), or the version you want to run (`v1.1.0` is the latest release, `async-september-21` is the version for current async rac
Hopefully `gui-redesign` also gets outdated soon, but in the mean time I'm keeping this way

2021-09-22 19:38 UTC, cjs8487 requested changes

2021-09-22 19:38 UTC, cjs8487 commented on README.md
> +    `/wbfs/The Legend of Zelda Skyward Sword [SOUE01]/`
This differs depending on which loader you're using from what I understand

2021-09-22 19:38 UTC, cjs8487 commented on README.md
> +You will need Python (3.8 for Windows) and pip (which should come with Python), as well as [WIT](https://wit.wiimm.de/download.html) (Windows users, download the Cygwin version; there's a simple inst
installing wit isn't necessary to run from source, only if you're not using the gui (and this may change in the future regardless)

2021-09-22 19:38 UTC, cjs8487 commented on README.md
> +4. Install the library dependencies:
remove "library"

2021-09-22 19:38 UTC, cjs8487 commented on changedflags.txt
> +Storyflags
personally I prefer md files to vanilla txt files, if only to have the option to format things if/when it becomes necessary. I'm not a stickler this, just a suggestion

2021-09-22 19:38 UTC, cjs8487 commented on README.md
> +    + A Wii, homebrewed to accept running games from a SD card, a USB drive or an external hard drive (for homebrewing, visit [this website](https://wii.guide))
I would phrase this as "A homebrewed Wii that can launch games from external medium, such as SD card, USB drive, or an external hard drive..."

2021-09-22 19:59 UTC, yannl35133 commented on changedflags.txt
> +Storyflags
I thought adding the two trailing spaces had the same effect as skipping a line (that is, making a new paragraph), but it appears not to be the case.
I will do that then, I agree that md files are usually more pleasant to read

2021-09-22 20:38 UTC, lepelog commented on README.md
> +4. Hit randomize (it may also take some time)
> The writing of the modified game to a playable format begins at 80% and usually takes the longest

I would not include that. In the future, it won't be needed anymore to repack the game for dolphin (since it can just run the dol from the modified-extract). And also for the time being, this info is not necessary, since the progress bar already indicates that it's repacking the game and since the progress bar moves, there shouldn't be much confusion about it

2021-09-22 20:40 UTC, cjs8487 commented on README.md
> +4. Hit randomize (it may also take some time)
We've had people express confusion at the fact that the progress is not super evenly distributed across the process (i.e. for me the last 20% takes 2-3 times longer than the first 80% on a good day), which is the reason I suggested that change, but I'm not particularly partial to it, and would be fine without it

2021-09-22 21:13 UTC, yannl35133 commented on README.md
> +    `/wbfs/The Legend of Zelda Skyward Sword [SOUE01]/`
I kept the example from the previous version

2021-09-22 21:31 UTC, cjs8487 requested changes

2021-09-22 21:31 UTC, cjs8487 commented on README.md
> +    + A homebrewed Wii that can launch games from an external medium, such as a SD card, a USB drive or an external hard drive. You can visit [this website](https://wii.guide) to get help homebrewing
Visit [homebrew site] for homebrewing information

2021-09-22 21:31 UTC, cjs8487 commented on README.md
> +3. Customize the settings to your liking; use permalinks to store and share selected settings
Change to "Customize the settings to your liking. You can use permalinks to store and share selected settings"

2021-09-22 21:31 UTC, cjs8487 commented on README.md
> +4. Hit randomize; this may also take a few minutes and the progress bar won't increase uniformly
Either explain the issue with the progress bar or leave it out (lepe says it shouldn't be necessary to mention because the progress bar should be sufficient).

2021-09-22 21:31 UTC, cjs8487 commented on README.md
> +Do **not** use the game's hero-mode files, it **will not work**. If you wish to play on hero mode, select the "hero mode" option in the randomizer. Then, even if they don't appear as such in the menu
Change Then to "When this option is selected" and remove "Please note that" and add "or not" to the end of he sentence

2021-09-22 21:35 UTC, lepelog commented on README.md
> +    + A homebrewed Wii that can launch games from an external medium, such as a SD card, a USB drive or an external hard drive. You can visit [this website](https://wii.guide) to get help homebrewing
I would just put it like `[https://wii.guide](https://wii.guide)`

2021-09-22 22:29 UTC, lepelog approved these changes

2021-09-22 22:39 UTC, cjs8487 approved these changes

2021-09-23 06:27 UTC, merged