Custom music support
ssrando/ssrando pull request #156
Opened 2022-02-21 16:08 UTC by Battlecats59

Patches music file length to 2GB for every file to prevent custom tracks from cutting off

2022-02-21 16:20 UTC, cjs8487 submitted a review, later dismissed
3/4 success rate is not sufficient to prove that this works without fail, especially when failures completely corrupt extracts

2022-02-21 16:24 UTC, Battlecats59 commented
CJ try to generate a seed with this version using the "Allow Custom Music" option, without custom music. That option should, in no way, corrupt your extract, it must be something else, related the music, that most likely caused it - then if that works you can try with the music and see if that corrupts your extract.

2022-03-13 02:46 UTC, Battlecats59 commented
Update: CJ's issue was determined to be not related to this patch, so this should be good to go

2022-03-14 22:11 UTC, lepelog requested changes

2022-03-14 22:11 UTC, lepelog commented on musicrando.py
> +                    track_len = 2147483647  # 0x7F FF FF FF - 2GB
```suggestion
                    track_len = 0x7FFFFFFF # - 2GB
```
Makes more sense as hex

2022-03-19 10:29 UTC, merged