Rework cube hints
ssrando/ssrando pull request #180
Opened 2022-04-30 16:42 UTC by YourAverageLink

Change the interaction such that barren hints factor their goddess cubes in as well and sots hints pointing to goddess chests display the zone of the associated cube instead of the chest. Also adds an option for modifying the sots hint to say it involves a cube.

2022-04-30 16:46 UTC, cjs8487 requested changes

2022-04-30 16:46 UTC, cjs8487 commented on options.yaml
> +  ui: option_hint_distribution
put the option before the distribution option, the distro option is intended to always be the last option for maximum backwards compatibility of permas when the list changes for whatever reason

2022-04-30 16:47 UTC, YourAverageLink commented on options.yaml
> +  ui: option_hint_distribution
It gets put before the distro in the permalink anyway it seems

2022-04-30 16:50 UTC, cjs8487 commented on options.yaml
> +  ui: option_hint_distribution
It shouldn't, if it does that is very strange. It may just look like it is depending on where it is in the bits for those characters

2022-05-01 10:36 UTC, lepelog requested changes
a few nitpicks

2022-05-01 10:36 UTC, lepelog commented on hints/hint_distribution.py
> +                if zone == "Mogma Turf":
```suggestion
                elif zone == "Mogma Turf":
```

2022-05-01 10:36 UTC, lepelog commented on hints/hint_distribution.py
> +        self.goddess_cube_zones = GODDESS_PRECISE_ZONES
this member is not needed at all, just use `GODDESS_PRECISE_ZONES` directly

2022-05-01 10:36 UTC, lepelog commented on logic/constants.py
> +    "Central Skyloft - Bazaar Goddess Chest": "Lanayru Sand Sea",
I think it would be better to have the information, in what region the cube is, added to `checks.yaml`

2022-05-01 10:50 UTC, YourAverageLink commented on logic/constants.py
> +    "Central Skyloft - Bazaar Goddess Chest": "Lanayru Sand Sea",
Fair enough, I was just worried that it would mean having to iterate through all of checks.yaml each time i need to fetch the cube zone

2022-05-01 11:32 UTC, lepelog commented on logic/constants.py
> +    "Central Skyloft - Bazaar Goddess Chest": "Lanayru Sand Sea",
You could do `self.rando.item_locations[loc]["cube_region"]`

2022-05-03 01:42 UTC, YourAverageLink commented
This is somewhat off-topic for the rest of this PR but it is just an option being added so it shouldn't conflict with anything else.

2022-05-03 06:17 UTC, lepelog requested changes

2022-05-03 06:17 UTC, lepelog commented on hints/hint_types.py
>          return {"location": self.location, "item": self.item, "type": "item"}
zone override needs to be added here

2022-05-03 06:17 UTC, lepelog commented
In general you shouldn't make 2 completely separate changes in the same PR, opening a new one is usually better or we end up with `gui-redesign` again

2022-05-03 11:48 UTC, YourAverageLink commented
My main concern was that I wanted to make the zone item hints compatible with new cube handling, and I was unsure if I made a new branch based off of this one if that meant we'd just end up with all the same commits again, plus the new one

2022-05-05 19:59 UTC, merged