Add additional sometimes hints
ssrando/ssrando pull request #194
Opened 2022-06-27 03:13 UTC by cjs8487

Adds the following sometimes hints
- Great Tree
- SV Dig Spot
- Turf Slide
- Slope Boulder Dig Spot (2x20)
- ET West Wing
- Fire Node Shortcut
- Lightning Node Ending
- Floria Chest
- AC East Wing
- SSH Brig Key

2022-06-27 22:20 UTC, lepelog requested changes
mostly agree with the added hints, I've voiced my concerns about a few locations in discord already so I won't repeat it here

2022-06-27 22:20 UTC, lepelog commented on checks.yaml
> +  text: the <r<hollow>> tree holds
The coloring pattern seems inconsistent to me, sometimes it spans everything but the verb at the end, sometimes it just highlights a seemingly unrelated word.

I prefer highlighting all the important parts, so `hollow tree` in this case.

Also imo, we can just use `great tree` here.

Unless I'm the only one complaining, we could first get the new sometimes hints in without cryptic messages and add them later.

2022-06-27 22:20 UTC, lepelog commented on checks.yaml
> +  text: the <r<lone west chest in the Ancient Cistern>> reveals
> Chest in East Part
> lone west chest

:thinking:

2022-06-29 16:01 UTC, YourAverageLink commented on checks.yaml
> +  text: the <r<lone west chest in the Ancient Cistern>> reveals
This is a bit of a nitpick, but i disagree with the use of "reveals" here too

2022-06-29 16:05 UTC, YourAverageLink commented
The lightning node sometimes hint is missing a containing verb (like holds, contains, etc.) after its description

2022-07-03 16:03 UTC, lepelog approved these changes

2022-07-03 16:03 UTC, merged