Add Option to Randomize Triforces
ssrando/ssrando pull request #214
Opened 2022-08-13 21:33 UTC by YourAverageLink

The Triforces of Courage, Wisdom, and Power may be randomized. If Triforce Required is enabled, the Triforce must be completed to open the door to Hylia's Realm. Triforces may be chosen to be vanilla, only in Sky Keep, or anywhere in the world. If the Triforce is not required, or they may appear anywhere, Sky Keep acts like an unrequired dungeon.

2022-08-18 22:50 UTC, lepelog commented on options.yaml
> +    - Sky Keep
Do we care about consistency with (Key|Map)sanity options and should use `Own Dungeon` here? I'm not really sure and I think it's fine how it is, just wanted to bring it up

2022-08-18 22:50 UTC, lepelog commented on patches.yaml
> +  - name: Scene Change for Wisdom layer
Scene changes can also be activated by sceneflags, so maybe just adding an `ScChang` with the right params could work?

2022-08-18 22:53 UTC, YourAverageLink commented on patches.yaml
> +  - name: Scene Change for Wisdom layer
Probably. I just copied the event that sends you out of the dungeon when the triforce is complete and adjusted its params to activate from the item sceneflags and connect to new entrypoints I made because I thought that was the simplest approach.

2022-08-28 15:36 UTC, YourAverageLink commented on patches.yaml
> +  - name: Scene Change for Wisdom layer
Update: I tried using `ScChang`s but that resulted in Link being sent to the silent realm state in sky keep. I think it should thus just be merged as it is.

2022-08-28 15:37 UTC, YourAverageLink commented on options.yaml
> +    - Sky Keep
I think Sky Keep is fine since they only ever appear in Sky Keep, unlike keys which exist in every dungeon (save for ET small keys)

2022-08-28 17:15 UTC, YourAverageLink commented on patches.yaml
> +  - name: Scene Change for Wisdom layer
Works with nontrial patch.

2022-08-28 17:20 UTC, lepelog requested changes

2022-08-28 17:20 UTC, lepelog commented on logic/constants.py
> +        ),  # for the purposes of restricting triforces to sky keep
```suggestion
        # for the purposes of restricting triforces to sky keep
        ("Triforce", "Sky Keep"),
```
If you put the comment above the line it's commenting on instead of after it, the formatter won't break lines stupidly like that

2022-09-13 18:46 UTC, lepelog approved these changes

2022-09-13 18:46 UTC, merged