Rupeesanity
ssrando/ssrando pull request #215
Opened 2022-08-14 18:12 UTC by elijah-thomas774

Adds Freestanding rupees that have a scene flag to the randomizer with an option.

current options: Vanilla / No quick Beetle / All

The current implementation of quick beetle is locked behind access to its materials. Will be changed after Raid's PR is verified.

When set to vanilla, the checks act as if they were not touched (no text box)

2022-08-18 22:39 UTC, lepelog requested changes

2022-08-18 22:39 UTC, lepelog commented on logic/logic.py
> +                else:
I think a comment which rupeesanity setting is in the else branch (the one without upgraded beetle) would make it more clear why those checks are forced to be vanilla.

Also I think it would be better to have the affected checks in a list in `logic/constants.py` since I'm not a fan of relying on parts of the name (which could change in the future)

2022-08-18 22:39 UTC, lepelog commented on gamepatches.py
> +                    temp_item_locations(rupee_check)
Is this supposed to have a `.pop` as well?

2022-08-18 22:58 UTC, elijah-thomas774 commented on logic/logic.py
> +                else:
This is Temporary until Progressive Items are added in. Once that gets merged in, itll need to change to be linked to the progressive tools option

2022-08-21 15:59 UTC, lepelog approved these changes

2022-08-21 16:10 UTC, merged