Boss key hints
ssrando/ssrando pull request #220
Opened 2022-09-18 22:12 UTC by Muzugalium

Added hints that point to the location of the boss key for required dungeons

2022-09-18 23:12 UTC, yannl35133 commented on hints/hint_distribution.py
> +            "boss key",
This string goes into JSON objects, so it's better for spaces to be replaced by `_`

2022-09-20 20:54 UTC, lepelog requested changes
- boss key hints have to be added to the changelog
- currently these changes do nothing so bk hints would need to be added to some existing hint distribution or a new one
- if a BK is on LMF BK chest or 3rd small key, that's always hinted and not counted towards the fixed number of BK hints, I guess that's intended?

2022-09-20 20:58 UTC, YourAverageLink commented
> - boss key hints have to be added to the changelog
> - currently these changes do nothing so bk hints would need to be added to some existing hint distribution or a new one
> - if a BK is on LMF BK chest or 3rd small key, that's always hinted and not counted towards the fixed number of BK hints, I guess that's intended?

The last two points are likely meant to be solved by new hint distributions. The dungeon always hints would be downgraded to sometimes hints or removed, since the BK hint sort of takes the role those hints used to fill.

2022-09-23 13:16 UTC, Muzugalium commented
For the last two points, yep exactly as Yal said

2022-09-23 22:55 UTC, lepelog approved these changes
I still think it's weird to add an unused feature (since it's not used in any distro) but I guess it's fine

2022-09-23 22:55 UTC, merged