Presets
ssrando/ssrando pull request #235
Opened 2022-10-07 01:49 UTC by cjs8487

Adds the ability for users to create, update, and manage their own presets, as well as a system for default presets distributed with the randomizer program. Presets are stored in JSON format (like saved settings) and could potentially be moved to remote storage in the future.

The defaults included with this are all 6 S2 modes, and a new beginner friendly preset.

Notes:
- Default presets are protected. They cannot be saved or deleted.
- Presets cannot share a name
- Order in the preset file matters, as that is the order they will be displayed. For user presets this should always be the order of creation
- Selecting a new preset **does not** overwrite the currently selected options until the load button is pressed
- Default presets are always loaded first, and then there is a divider in the selection list

2022-10-07 02:07 UTC, YourAverageLink commented on gui/default_presets.json
> +    "S2 - 3D Open": {"starting-tablet-count": 3, "open-thunderhead": "Ballad", "starting-sword": "Goddess Sword", "required-dungeon-count": 3, "imp2-skip": true, "empty-unrequired-dungeons": true, "b
```suggestion
    "S2 - 3D Open": {"starting-tablet-count": 3, "open-thunderhead": "Open", "starting-sword": "Goddess Sword", "required-dungeon-count": 3, "imp2-skip": true, "empty-unrequired-dungeons": true, "banned-types": ["peatrice", "goddess", "medium", "expensive"], "triforce-required": false, "triforce-shuffle": "Vanilla", "seed": -1, "hero-mode": true, "randomize-entrances": "None", "randomize-trials": false, "start-with-pouch": true, "no-spoiler-log": true, "max-batreaux-reward": 50, "shop-mode": "Randomized", "rupoor-mode": "Added", "rupeesanity": "Vanilla", "gondo-upgrades": false, "got-start": "Lowered", "got-sword-requirement": "Master Sword", "got-dungeon-requirement": "Required", "open-lmf": "Open", "skip-horde": false, "skip-g3": false, "skip-demise": false, "map-mode": "Own Dungeon - Restricted", "small-key-mode": "Lanayru Caves Key Only", "boss-key-mode": "Own Dungeon", "logic-mode": "BiTless", "enabled-tricks-bitless": [], "enabled-tricks-glitched": [], "song-hints": "None", "fix-bit-crashes": false, "impa-sot-hint": false, "sword-dungeon-reward": false, "open-et": true, "demise-count": 1, "cutoff-gameover-music": false, "cube-sots": false, "precise-item": false, "shuffle-trial-objects": "None", "hint-distribution": "S2 - 3D"},
```
Also, while not specific to Open, you forgot to remove cutoff gmaeover music from the saved settings

2022-10-07 22:14 UTC, lepelog requested changes
KolokChamp

2022-10-07 22:14 UTC, lepelog commented on gui/randogui.py
> +        # prevent loading the new preset option
I don't know anything about QT, but how hard/how much work would it be to just disable the buttons when you're not supposed to click them? I think that would be nicer to use

2022-10-07 22:14 UTC, lepelog commented on gui/default_presets.json
> +    "S2 - Keysanity": {"starting-tablet-count": 3, "open-thunderhead": "Ballad", "starting-sword": "Goddess Sword", "required-dungeon-count": 3, "imp2-skip": true, "empty-unrequired-dungeons": true,
Remove `no-spoiler-log` from all of them

2022-10-07 22:14 UTC, lepelog commented on gui/randogui.py
> +        with open("gui/default_presets.json") as f:
```suggestion
        with (RANDO_ROOT_PATH / 'gui' / 'default_presets.json').open() as f:
```

otherwise the exe breaks

2022-10-09 20:41 UTC, cjs8487 commented on gui/randogui.py
> +        # prevent loading the new preset option
I left the checks in just in case there's a way around QTs disable, but the buttons now enable/disable as appropriate

2022-10-09 20:52 UTC, cjs8487 commented on gui/randogui.py
> +                "dry-run",
I combined both ideas - all non-permalink options should be excluded from presets (at least as of now), however there are some edge case options, such as `no-spoiler-log`, where the option is in the permalink but should be excluded from presets as well. This setup will give us the flexibility to handle both cases, and we can always fall back to a full exclusionary version in the future if the need arises

2022-10-09 21:15 UTC, yannl35133 commented on gui/randogui.py
> +            with open(self.user_presets_path) as f:
Is this a purely relative file opening ? Shouldn't you at least start from `RANDO_ROOT_PATH` ?

2022-10-09 21:15 UTC, yannl35133 commented on options.py
> +            if not include_nonperma and "permalink" in option and not option["permalink"]:
```suggestion
            if exclude_nonperma and option.get("permalink", True) is False:
```
Of course the `exclude_nonperma` would have to be reflected at all (1) call sites

2022-10-09 21:36 UTC, cjs8487 commented on gui/randogui.py
> +            try:
This is hardly the place for such a refactor. If we decide that is the path forward it should developed and tested as an isolated set of changes

2022-10-09 21:36 UTC, cjs8487 commented on gui/randogui.py
> +            with open(self.user_presets_path) as f:
It’s purely relative. It will always be at the root of the source or in the same directory as the exe. It’s the same as the settings file

2022-10-11 16:06 UTC, lepelog approved these changes

2022-10-13 01:40 UTC, merged