Chest dowsing matches contents
ssrando/ssrando pull request #257
Opened 2022-10-23 04:10 UTC by YourAverageLink

Adds chest dowsing functionality, currently with treasure dowsing (unlocked from the start provided you have a sword)
- None doesn't put dowsing on any chest
- All puts dowsing on all chests (except goddess rn)
- Matches Contents points to chests with progress items (except goddess rn)

Treasure dowsing also no longer points to freestanding treasure

2022-10-23 08:19 UTC, lepelog requested changes

2022-10-23 08:19 UTC, lepelog commented on asm/patches/custom_funcs.asm
> +
please move this function to the bottom of the custom functions in main.dol, to not pollute the diff

2022-10-23 08:19 UTC, lepelog commented on asm/patches/ss_necessary.asm
> -
This doesn't seem intentional

2022-10-23 11:51 UTC, YourAverageLink commented on asm/patches/ss_necessary.asm
> -
That might be git being dumb since I think I copied from master before this patch was merged?

2022-10-23 17:39 UTC, lepelog requested changes

2022-10-23 17:39 UTC, lepelog commented on CHANGELOG.md
> +  - None: Like currently (treasure dowsing will not pick up on any chest)
Shouldn't this be the "Vanilla" option, so it should point to chests containing treasure?

2022-10-23 17:39 UTC, lepelog commented on asm/patches/ss_necessary.asm
> +; allow dowsing even if item isn't rupee, key piece, or treasure
```suggestion
; always register the dowsing target, this is safe since a non initialized dowsing target
; has dowsing index 8, so it's rejected from registering and unregistering
```

the comment wasn't accurate at all

2022-10-23 17:39 UTC, lepelog commented on ssrando.py
> +                plcmt_file.chest_dowsing[k] = v in self.logic.all_progress_items
I think this belongs more into logic

2022-10-23 17:41 UTC, yannl35133 commented on CHANGELOG.md
> +  - None: Like currently (treasure dowsing will not pick up on any chest)
It isn't currently, it could [should be]

2022-11-03 20:17 UTC, lepelog commented on CHANGELOG.md
> +  - None: Main quest dowsing will not point to chests
I think this should also mention that "None" preserves vanilla treasure/rupee dowsing behaviour

2022-11-10 18:24 UTC, merged