Add Support for Custom Hint Distributions
ssrando/ssrando pull request #272
Opened 2022-11-10 05:46 UTC by cjs8487

This adds support for user provided custom hint distributions.  Users are assumed to have functional knowledge of how to create their own distributions when using this option. Error messages regarding invalid distributions are deliberately vague as there is no specific error checking on distributions (currently the only time a distribution can explicitly raise an error is when it un able to be read due to bad JSON). There can only be a single active custom distribution at a time, and it will always be sourced from `custom_hint_distribution.json`. The non-whitespace contents of the file are added to the randomizers hash process when this option is enabled.

Additionally a secondary error check has been added to the UI, allowing the randomizer's initialization process to raise errors and have them handled properly by the UI. This should also help catch some edge error cases that may pop up for end users and allow us to debug them more effectively.

2022-11-11 11:34 UTC, lepelog requested changes

2022-11-11 11:34 UTC, lepelog commented on ssrando.py
> +            if not os.path.exists("custom_hint_distribution.json"):
I would refactor this and add `CUSTOM_HINT_DISTRIBUTION_PATH = Path("custom_hint_distribution.json")` to paths.py and then import that everywhere (that also allows to use `CUSTOM_HINT_DISTRIBUTION_PATH.open('r')` and `CUSTOM_HINT_DISTRIBUTION_PATH.exists()`)

2022-11-11 11:34 UTC, lepelog commented on ssrando.py
> +                    current_hash.update(line.strip(" \n").encode("ASCII"))
```suggestion
            with open("custom_hint_distribution.json") as f:
                normalized_json = json.dumps(json.load(f))
                current_hash.update(normalized_json.encode('ASCII'))
```
Checking a bit for how to hash dictionaries in python, it seems like most recomment just dumping to json and hashing that. This should also get rid of line ending problems

2022-11-11 11:34 UTC, lepelog commented on hints/hint_distribution.py
> +        except:
I think it might be better to at least print the original exception

2022-11-11 15:27 UTC, YourAverageLink reviewed
Dunno if you want to given there's a new logic PR that addresses it and new logic is hopefully around the corner, but it would be nice if in this same PR, n-hints-per-stone functionality could be included while we're at it.

2022-11-13 12:03 UTC, lepelog commented
> 



> Dunno if you want to given there's a new logic PR that addresses it and new logic is hopefully around the corner, but it would be nice if in this same PR, n-hints-per-stone functionality could be included while we're at it.

This has nothing to do with that, let's not put a bunch of unrelated things into one PR

2022-11-20 19:42 UTC, lepelog approved these changes

2022-12-06 13:30 UTC, lepelog commented
can be merged after conflicts are resolved

2023-06-14 22:50 UTC, merged