Exclude Individual Locations
ssrando/ssrando pull request #282
Opened 2022-11-20 16:34 UTC by cjs8487

UI isn't currently the greatest for this but it will be addressed with the remainder of the UI changes

2022-11-20 19:38 UTC, lepelog requested changes
I think it would make sense to have the labels `Include Locations` and `Exclude Locations`, otherwise it's ambiguous

2022-11-20 19:38 UTC, lepelog commented on gui/randogui.py
> +        self.excluded_locations_model.sort(0)
Does it make sense to just default sort them? I think it makes more sense to have them sorted by their order in `checks.yaml`

2022-11-20 19:38 UTC, lepelog commented on options.py
> +with (RANDO_ROOT_PATH / "checks.yaml").open("r") as f:
You can use `read_yaml_file_cached` here

2022-11-20 19:54 UTC, cjs8487 commented on gui/randogui.py
> +        self.excluded_locations_model.sort(0)
The current order in `checks.yaml` is semi-arbitrary (and for parts of Skyloft checks in the same region aren't even grouped together). By default, the model only seems to support alphabetical sorting, but I imagine we could probably write a custom sort order, or even just recreate the model every time there's a change to preserve the order rather than sorting it, however both of those will likely result in a (likely minor) performance hit

2022-11-20 19:57 UTC, lepelog commented on gui/randogui.py
> +        self.excluded_locations_model.sort(0)
The change to the check order was an accident that should probably be fixed. Can you just enumerate all the check names and sort on the number? It doesn't need to be displayed

2022-11-23 17:46 UTC, lepelog approved these changes

2022-12-06 13:29 UTC, merged