Fi menu overhaul
ssrando/ssrando pull request #306
Opened 2022-12-31 19:21 UTC by Muzugalium

2023-01-01 01:23 UTC, Muzugalium commented
Found a bug with the dungeon status where maps are always shown as unobtained, will try and fix tomorrow

2023-01-08 23:15 UTC, lepelog requested changes

2023-01-08 23:15 UTC, lepelog commented on asm/custom-functions/src/lib.rs
> +            }
```suggestion
            let key_count = if dungeon_index == 14 /* ET */ {
                unsafe { getKeyPieceCount() }
            } else {
                dungeon_global_key_count(dungeon_index)
            };
```

2023-01-08 23:15 UTC, lepelog commented on gamepatches.py
>                      cur_line += part + " "
Use `break_lines` from `textbox_utils`(it didn't exist when this code was written, but would be a good cleanup)

2023-01-12 21:18 UTC, Muzugalium commented on gamepatches.py
>                      cur_line += part + " "
Done ^^

2023-01-12 21:19 UTC, Muzugalium commented on asm/custom-functions/src/lib.rs
> +            }
Also done ^^

2023-01-13 03:39 UTC, CovenEsme commented
Tested in race today - no issues found.

2023-01-13 09:43 UTC, merged