Add option to patch BiT
ssrando/ssrando pull request #343
Opened 2023-02-08 18:42 UTC by CovenEsme

Adds an option to force the RELOADER_TYPE when loading the title screen so that it is no longer possible to perform the Back in Time (BiT) glitch. Additionally, removes the now useless "Hero Mode" ui toggle.

2023-02-08 18:52 UTC, lepelog commented on options.yaml
> +  ui: option_patch_bit
Would it make sense to merge this with `fix-bit-crashes` into a single setting? With choices like
- no changes
- make BiT not crash
- make BiT not possible at all
but better names obviously

2023-02-08 18:55 UTC, CovenEsme commented on options.yaml
> +  ui: option_patch_bit
Could do something like:
* Disable BiT
* Vanilla
* Fix BiT Crashes

2023-02-19 00:39 UTC, lepelog requested changes

2023-02-19 00:39 UTC, lepelog commented on options.yaml
> +        Disable BiT: Forces the title screen to reload fully - making all BiT tricks impossible.
```suggestion
        Disable BiT: Makes it impossible to activate BiT.
```
`Forces the title screen to reload fully` is not accurate at all, the title screen loads fully and properly in any case, the difference is really if link respects the params of the entrance, that are supposed to trigger an infinite cutscene

2023-02-19 00:39 UTC, lepelog commented on options.yaml
> +        Fix BiT Crashes: Does not load some arcs in BiT when all file slots are filled to make all areas accessible in BiT."
Not sure how to word it, but maybe it should stress that all the file slots need to be filled *before* activating BiT?

2023-03-14 15:05 UTC, CovenEsme commented
Has been tested in several seeds and races. Patched BiT worked in the monthly no-BiT race and Vanilla worked in subsequent BiT races.

2023-03-14 20:17 UTC, merged