Add Tips to the Progress Dialog
ssrando/ssrando pull request #355
Opened 2023-02-19 23:52 UTC by cjs8487

Adds a set of tips to the randomization progress dialog that cycle through over time. Looking for more tips to add to the list prior to merging

2023-02-20 00:12 UTC, YourAverageLink requested changes
Just adding a few more that I think would be useful.

2023-02-20 00:12 UTC, YourAverageLink commented on gui/progressdialog.py
> +    "Enabling tricks is a fun way to expand the logical possiblities of the randomizer, but some tricks can greatly incease the difficulty of seeds",
```suggestion
    "Enabling tricks is a fun way to expand the logical possiblities of the randomizer, but some tricks can greatly incease the difficulty of seeds.",
    "Fi can give you some helpful information about the seed, such as which dungeons are required and how many keys you have. You can always call her with D-pad down, even without a sword.",
    "Hold down the B button to quickly advance text.",
```

2023-02-20 00:12 UTC, YourAverageLink commented on gui/progressdialog.py
> +    "Think you're stuck somewhere with no way to get back to safety? Look around for a bomb flower. Dying will safely return you to the last statue you saved at or the last loading zone you crossed",
```suggestion
    "Think you're stuck somewhere with no way to get back to safety? Look around for a bomb flower. Dying will safely return you to the last statue you saved at or the last loading zone you crossed.",
```

2023-02-20 01:43 UTC, YourAverageLink commented on gui/progressdialog.py
> +    "Think you're stuck somewhere with no way to get back to safety? Look around for a bomb flower. Dying will safely return you to the last statue you saved at or the last loading zone you crossed,"
```suggestion
    "Think you're stuck somewhere with no way to get back to safety? Look around for a bomb flower. Dying will safely return you to the last statue you saved at or the last loading zone you crossed.",
```

2023-02-20 01:43 UTC, YourAverageLink commented on gui/progressdialog.py
> +    "Think you're stuck somewhere with no way to get back to safety? Look around for a bomb flower. Dying will safely return you to the last statue you saved at or the last loading zone you crossed,"
Sorry i probably typo'd that comma

2023-02-20 01:44 UTC, cjs8487 commented on gui/progressdialog.py
> +    "Think you're stuck somewhere with no way to get back to safety? Look around for a bomb flower. Dying will safely return you to the last statue you saved at or the last loading zone you crossed,"
Nah that was me lmfao. I'l make the change but I'm not gonna push quite yet

2023-03-31 22:45 UTC, lepelog approved these changes
If the tip is wider than 400px the dialog appears in the top left corner of the screen for me, but that's probably just a linux thing, looks good otherwise.

The tips themselves look good.

2023-04-07 08:33 UTC, lepelog approved these changes

2023-04-08 10:03 UTC, merged