Fi Hints
ssrando/ssrando pull request #359
Opened 2023-03-08 04:36 UTC by YourAverageLink

Adds Fi as a hint source
- She holds gossip stone hints, and hints are placed on her first before filling any remaining stones
- They may be accessed from her menu (Information -> Hints)

2023-03-08 08:01 UTC, yannl35133 requested changes
Remarks on the logic part

2023-03-08 08:01 UTC, yannl35133 commented on logic/hints.py
> +        self.logic.placement.fi_hints |= set([hintname for hintname in fi_hints])
Where is this used ? `HINTS` are the gate to requirements for hint logic, if you make it no-logic you shouldn't bother with those. `placement.fi_hints` looks unused except locally, so i don't understand why it exists a a full field
```
        placed_fi_hints = {
            FI_HINTS: FiHintWrapper(fi_hints)
        }
```
This should do

2023-03-08 23:42 UTC, YourAverageLink commented on hints/hint_distribution.py
> +                "Selected hint distribution must have at least 1 hint per stone or at least 1 Fi hint. "
Holdover from when 0 hint stones used to error... I guess it doesn't need to stay.

2023-04-07 14:29 UTC, lepelog requested changes

2023-04-07 14:29 UTC, lepelog commented on logic/hints.py
> +        self.logic.placement.fi_hints |= set([hintname for hintname in fi_hints])
This seems unused? Remove

2023-04-07 14:29 UTC, lepelog commented on logic/logic.py
> +    fi_hints: Set[Hint | GossipStoneHintWrapper] = field(default_factory=set)
Unused?

2023-04-07 14:29 UTC, lepelog commented on gamepatches.py
> +        for i in range(0, len(self.placement_file.hints["Fi"]), 8):
```suggestion
        for i in range(0, len(self.placement_file.hints[FI_HINTS]), 8):
```

2023-04-07 14:29 UTC, lepelog commented on hints/hint_distribution.py
>          assert self.nb_hints <= MAX_HINTS
"MAX_HINTS" now also has the max fi hint count, but that means a lot more gossip stone hints are possible now, that isn't intended, right?

2023-04-07 14:29 UTC, lepelog commented on hints/hint_types.py
> +@dataclass
I think this can be removed, cause you override `__init__` anyways

2023-04-07 15:05 UTC, YourAverageLink commented
Since no complete alternative has been given for how to implement these, I'll mark this as ready for review rather than draft.

2023-04-29 14:49 UTC, CovenEsme commented
Has been tested in many seeds with different settings (blitz tourney settings, mine and Muzu's co-op settings, co-op + tadtones, co-op + tadtones - cubes) and seems to hold up well.

I've also genned a few logs with some more extreme settings to see how the edge cases are handled.

Seeds with no locations excluded seem to work. However, the always *and* sometimes hints take precedence over the path hints. Genning a seed with 3 or more dungeons required and no locations excluded only gives 2 path hints. Not sure if this is the intended compromise.

Seeds with no dungeons, no batreaux, beedle cheap, all the always and sometimes hinted locations excluded, all starting items works fine. You get 2 barren hints and the rest are filled with random hints.

Not sure what the concerns with the implementation details were so I can't comment on those.

tl;dr: always and sometimes(?) hints take priority over path hints which can lead to fewer path hints than required dungeons (in extreme settings). Otherwise, it works great :p

2023-06-14 22:59 UTC, merged