Fix Beedle's Shop items being hidden in the table
ssrando/ssrando pull request #361
Opened 2023-03-15 03:22 UTC by CovenEsme

Fixes the longstanding issue where the majority of the items in Beedle's Shop would appear mostly in the table. Items should now appear, clearly visible, on top of the table. They should also be nicely scaled both on the table and when viewed close up before purchasing.

2023-03-17 00:04 UTC, lepelog requested changes

2023-03-17 09:38 UTC, CovenEsme commented on asm/patches/shopsanity.asm
> +.float 1.5
No, this is leftover. I wasn't going to patch the buyDecideScale originally but some of the bigger items (b-wheel, boss keys) looked a bit ridiculous.

2023-03-17 09:48 UTC, CovenEsme commented
Updated from feedback :p

2023-03-18 10:58 UTC, lepelog approved these changes

2023-03-18 10:59 UTC, merged