Random starting entrance
ssrando/ssrando pull request #364
Opened 2023-03-19 19:40 UTC by CovenEsme

Adds an option to start at a random birb statue (or Link's bedroom.). Logic Should™️ account for this. Also adds Fi Warp to return to your starting entrance.

For dev purposes, hardcoding a starting entrance has been made quite simple. Search for "HARDCODE STARTING ENTRANCE HERE" in `gamepatches.py` and replace the stage, room, layer, and entrance as needed.

2023-07-21 00:50 UTC, lepelog requested changes

2023-07-21 00:50 UTC, lepelog commented on asm/custom-functions/src/lib.rs
> +struct StartInfo {
this is missing `#[repr(C)]`, rust can reorder fields otherwise

2023-07-21 00:50 UTC, lepelog commented on asm/custom-functions/src/lib.rs
> +    let start_info = unsafe { &*(0x802DA0E0 as *const StartInfo) };
It probably makes sense to have a function to get a reference to the start info, to not duplicate the address

2023-07-21 00:50 UTC, lepelog commented on asm/patches/ss_necessary.asm
> +; .org 0x801bb960 ; Change starting stage
The commented out code can get deleted, right?

2023-07-21 09:12 UTC, CovenEsme commented on logic/constants.py
> +PROVINCES = (FARON_PROVINCE, ELDIN_PROVINCE, LANAYRU_PROVINCE, THE_SKY)
They are used for the `limit-starting-location` option (or w/e I called it). Allows us to filter the entrances based on what tablets you start with

2023-07-22 12:23 UTC, lepelog commented on logic/constants.py
> +PROVINCES = (FARON_PROVINCE, ELDIN_PROVINCE, LANAYRU_PROVINCE, THE_SKY)
I meant `PROVINCES` specifically, the other strings are used

2023-07-22 12:30 UTC, CovenEsme commented on logic/constants.py
> +PROVINCES = (FARON_PROVINCE, ELDIN_PROVINCE, LANAYRU_PROVINCE, THE_SKY)
Oh, yeah, that's probably leftover then

2023-07-23 10:20 UTC, CovenEsme commented
Changes made

2023-07-25 20:30 UTC, CovenEsme commented
Tested bird statue random start in a full seed playthrough with the recent changes, no issues found

2023-07-31 23:14 UTC, merged