Starting Item Options
ssrando/ssrando pull request #377
Opened 2023-04-03 19:43 UTC by CovenEsme

Aims:
* Add additional start items that were missed first time round (extra wallets and crystal packs)
* Add options to start with max bugs and treasures
* Allow starting with a full wallet
* Add option for wallet upgrades to come pre-filled with Rupees
* Add initial options for starting with a shield and bottles (not how I envision this looking in the future but, as a highly requested feature, it's good solution for now)

Details:
* The additional items work the same as the others. Crystal packs are chosen with a spin box as discussed
* Starting: rupees, health, interface choice, bugs, treasures, shield, and bottles are stored in a bitfield at the end of the startflags (this was already *kinda* the case for the interface choice)
* Starting shield and bottles are options separate from the main item list (this is due to their "temporary" status)
  * These options are "temporary" as we hope to create a popout dialog for broader starting pouch item support later
* If enabled, Hylian Shield is always placed in the top-most pouch slot
* Bottles fill the remaining pouch slots
* If there are more starting pouch items than available pouch slots, items are still placed in the pouch inventory and will become immediately available when a pouch upgrade is found (this could be changed to have extra items get sent to the item check but that's a little more work and I want to get feedback first :p)

Tests needed:
* Verify that starting with a full wallet works for all combinations (I'm pretty sure I did this but extra verification would be great)
* Verify you get the correct amount of rupees when obtaining a wallet upgrade
* Verify starting with a shield/bottles works as expected
* Verify I didn't break existing starting health or interface choice stuff

2023-04-03 20:43 UTC, lepelog requested changes

2023-04-03 20:43 UTC, lepelog commented on asm/custom-functions/src/lib.rs
> +        }
```suggestion
        for counter in 10..=21 {
            unsafe {
                increaseCounter(counter, 99);
                setFlagForItem(counter + 131); // counter + (itemflag - counter)
            }
        }
```

2023-04-03 20:43 UTC, lepelog commented on asm/custom-functions/src/lib.rs
> +        }
```suggestion
        for counter in 22..=37 {
            unsafe {
                increaseCounter(counter, 99);
                setFlagForItem(counter + 139); // counter + (itemflag - counter)
            }
        }
```
..= is an inclusive range

2023-04-03 20:43 UTC, lepelog commented on asm/custom-functions/src/lib.rs
> +    }
```suggestion
    for _bottles_added in 0..(additional_start_options_2 & 0x7) {
        pouch_items[next_pouch_index] = 153; // ID for bottles
        next_pouch_index += 1;
    }
```
I'll look at this again, this array access probably creates an unnecessary panicking branch, since the index can be out of bounds

2023-04-03 20:43 UTC, lepelog commented on gamepatches.py
> -        )
Why inline this statement? Imo it was fine how it was, also slightly clearer imo

2023-04-03 20:43 UTC, lepelog commented on gamepatches.py
> +        additional_start_options = self.starting_rupee_count // 100
Imo it makes sense to have the comment about only storing multiples of 100 here too

2023-04-06 11:04 UTC, Muzugalium commented
Tested:
-Starting with full wallet with several different combinations of wallet upgrades and extra wallet- works as expected
-Starting with different combinations of hylian shield and number of bottles along with different combinations of starting pouches (and picking up pouches in game)- works as expected
-Starting with max bugs, max treasures, both, and neither- works as expected
-Starting with various amounts of crystal packs- works as expected
-Picking up various wallet upgrades and extra wallets with "pre-filled wallets" on- works as expected

2023-04-07 00:04 UTC, merged