Fix skipper der bug
ssrando/ssrando pull request #383
Opened 2023-04-05 12:49 UTC by CovenEsme

Fixes bug were Skipper's "To the Sandship" dialog option opens up after beating Tentalus - even in DER.

Removes extra entrance to SSH after beating Tentalus (causes problems with DER).

2023-04-05 20:12 UTC, lepelog requested changes
Looks good apart from the "typos", needs a test to make sure the sandhip dock loadzone works both before and after defating tentalus, when that boss is in another dungeon entrance

2023-04-05 20:12 UTC, lepelog commented on patches.yaml
> +  - name: Remove excess entrance to Sadship (layer 2)
```suggestion
  - name: Remove excess entrance to Sandship (layer 2)
```
typo

2023-04-05 20:12 UTC, lepelog commented on patches.yaml
> +  - name: Remove excess entrance to Sadship (layer 3)
```suggestion
  - name: Remove excess entrance to Sandship (layer 3)
```

2023-04-05 20:12 UTC, lepelog commented on patches.yaml
> +  - name: Remove excess entrance to Sadship (layer 4)
```suggestion
  - name: Remove excess entrance to Sandship (layer 4)
```

2023-04-05 20:12 UTC, lepelog commented on patches.yaml
> +  - name: Remove excess entrance to Sadship (layer 5)
```suggestion
  - name: Remove excess entrance to Sandship (layer 5)
```
typo

2023-04-06 16:13 UTC, Muzugalium commented
Tested:
-Shooting sandship down- entered correct dungeon
-Completing shipyard and re-entering the docked sandship- entered correct dungeon
-Completing pirates and re-entering the docked sandship- enteered correct dungeon
-Completing sandship in AC entrance and re-entering docked sandship- entered correct dungeon

2023-04-06 19:32 UTC, merged