Tadtonesanity
ssrando/ssrando pull request #402
Opened 2023-04-25 16:46 UTC by CovenEsme

Aims:
* Add support for custom items
* Add 17 "Group of Tadtones" items to the pool
* Add 17 checks to Flooded Faron Woods (one for each vanilla tadtone group)
* Add option to toggle Tadtonesanity
* Allow entry into Flooded Great Tree without Water Scale
  * Add a bomb flower on the lilypad in-front of Bucha to prevent softlocks

Details:
* `keysanity.asm` has been renamed to `custom_items.asm`
* Custom functions have been added so that custom items can be more easily added in the future
  * This includes setting custom models for items and should be able to be used for adding the Sailcloth item (with its correct model)
* Logic for entering Flooded Great Tree has been updated to no longer require Water Scale
* As you need to watch the tadtones jingle in Flooded Faron Woods before getting the Water Dragon's Reward check, logic takes into account that you need access to Flooded Faron Woods in addition to Flooded Great Tree
* The Tadtone dowsing cutscene trigger has been removed since tadtone dowsing is a start flag. This can, ofc, be reversed if we ever want to make getting dowsing abilities checks
* The Cranioc cutscene trigger has been removed as it is buggy when getting it after already having gotten the Water Dragon's Reward check

Tests Needed:
* Verify getting a "Group of Tadtones" item from chests, npcs, freestanding, etc works as expected
* Verify the item get textbox shows the correct number of tadtones remaining
* Verify Fi shows you to have the correct number of tadtones
* Verify you can enter and leave Flooded Great Tree via the Water Dragon - even if you don't have Water Scale
* Verify you can get the Water Dragon's Reward check only after getting all 17 tadtones and that you can only get it once
  * You must watch the tadtones jingle in Flooded Faron Woods first (the one cutscene I won't remove xD)
* Verify you can get each tadtone check in Flooded Faron Woods both before getting the Water Dragon's Reward check and after
  * Getting all 17 should **not** start the tadtones jingle
  * The on-screen music scroll should update (even after getting the Water Dragon's Reward check)
  * The Cranoic and Tadtone dowsing cutscenes shouldn't play

Known Issues:
* The preview for the "Group of Tadtones" item in Beedle's Shop is raised higher than usual. This is true of other existing items and cannot be changed right now (not until someone looks into it at least)

2023-04-27 23:44 UTC, lepelog requested changes
cool stuff :+1:

2023-04-27 23:44 UTC, lepelog commented on checks.yaml
> +    - stage/F103/r0/l2/Clef/0x01A4
Is it possible to identify them by something like their sceneflag or group? Cause then we don't need to write out every tadtone

2023-04-27 23:44 UTC, lepelog commented on gamepatches.py
> +            lambda x: x["name"] == "Clef" and x["id"] == id,
I guess you *can* patch multiple Tadtones here, (if the group has something in common). If that works, I think it's better than having all the ids in checks.yaml

2023-04-27 23:44 UTC, lepelog commented on asm/patches/ss_necessary.asm
> +; Story Flag #953 (0x03B9) - US from 805A9B7E 0x01 to 805A9B7E 0x40
what's at this address, just padding after the normal storyflags?

2023-04-27 23:44 UTC, lepelog commented on asm/custom-functions/src/lib.rs
> +            let tadtone_groups_left = 17 - storyflag_get_to_value(953);
```suggestion
            let tadtone_groups_left: u32 = 17.saturating_sub(storyflag_get_to_value(953)).into();
```
Just to be safe, to not wrap around (side note, this only wraps around in release mode, in debug mode it would panic instead)
Also you can just use `into` here to get rid of the casts later, by just turning the u16 into u32 here

2023-04-27 23:44 UTC, lepelog commented on asm/custom-functions/src/lib.rs
> +fn storyflag_get_to_value(flag: u16) -> u16 {
```suggestion
fn storyflag_get_value(flag: u16) -> u16 {
```
or only `storyflag_get`, idk

2023-04-29 13:21 UTC, CovenEsme commented on asm/patches/ss_necessary.asm
> +; Story Flag #953 (0x03B9) - US from 805A9B7E 0x01 to 805A9B7E 0x40
Yeah. The normal storyflags start at index 0 and the counter storyflags start at the end and fill up space backwards. This uses the in-between space (after the last counter `Story Flag #1087 (0x043F) - US from 805A9B81 0x40 to 805A9B80 0x04`)

2023-04-29 14:12 UTC, CovenEsme commented on gamepatches.py
> +            lambda x: x["name"] == "Clef" and x["id"] == id,
This appears to work :p

2023-04-29 14:15 UTC, CovenEsme commented
Updated from feedback :p

2023-05-10 18:22 UTC, lepelog approved these changes
looks good, only one nit and then this should be good to go

2023-05-10 18:22 UTC, lepelog commented on gamepatches.py
> +        next_clef = next(clefs, False)
```suggestion
    for clef in clefs:
        clef["anglez"] = mask_shift_set(clef["anglez"], 0xFFFF, 0, itemid)
```

2023-05-24 11:33 UTC, merged