Dusk Relic Shuffling (For real this time)
ssrando/ssrando pull request #413
Opened 2023-06-07 06:49 UTC by YourAverageLink

The old PR seems super borked so I'm opening this one from a new branch with significantly fewer commits.

Adds functionality to shuffle dusk relics in each silent realm (this is a continuation of an old Peppernicus PR)

Silent Realms can have up to 10 dusk relics turned into shuffled items. These items can swap locations with other trial objects with the trial object shuffle setting as well. Should you enable less than the maximum amount, the relics which contain items are chosen at random (the rest will have dusk relics as usual). Trial gates will remain open even after the trial has been completed (upon re-entry, you cannot obtain the trial reward again, nor will the treasure items respawn).

Song Hints still exist; they point specifically to the trial reward. Silent realms are now valid regions for other hint types. If song hints are disabled, trial rewards are now sometimes hints (rather than always hints).

2023-06-28 05:03 UTC, CovenEsme reviewed
Looks good to me. Testing seems to be going well since the Eldin trial bug was fixed. I have found it kinda difficult to distinguish the colours of the light beams on the items vs tears but I don't think there's anything we can do about that

2023-06-28 05:03 UTC, CovenEsme commented on SS Rando Logic - Glitched Requirements.yaml
> +  Can Access Lanayru Silent Realm
```suggestion
```
Duplicate entry

2023-07-21 01:02 UTC, lepelog requested changes

2023-07-21 01:02 UTC, lepelog commented on gamepatches.py
> +        #     self.treasuresanity_in_silent_realms()
leftover

2023-07-21 01:02 UTC, lepelog commented on gamepatches.py
> +            stamina_list = []
are these actually used?

2023-08-06 12:49 UTC, goldendevil1711 commented
I may be dumb, but: is there a link to a build with just dusk relic shuffle (and not the other beta-features builds)?  I'm willing to test but given the but I had with beta-features yesterday I want to make sure I don't run into any weird conflicts.

2023-08-06 12:53 UTC, CovenEsme commented
Yep! Each PR has a build link near the top of the comment chain. You can find it here:

https://github.com/ssrando/ssrando/pull/413#issuecomment-1580024370

2023-08-06 12:53 UTC, CovenEsme commented
It'll automatically update to be the latest build too

2023-08-25 18:25 UTC, YourAverageLink commented
Please hold off on merging this until the weekly is over (so the version and settings string are still up to date and the tracker works correctly).

2023-08-25 18:25 UTC, merged