Fix some duplicated locations
ssrando/ssrando pull request #512
Opened 2023-12-24 22:16 UTC by robojumper

These were found by a simple "unused location" check in the new-logic tracker (area locations that don't correspond to a check and also aren't mentioned in any other expressions). This fixes the ones that very obviously look like bugs -- there are more unused locations but some of them are simply unused in a benign way.

2023-12-24 22:26 UTC, yannl35133 commented
I suspect the "benign" unused locations are hooks for BiT logic in the future, but these definitely look like errors

2023-12-24 22:27 UTC, robojumper commented on logic/requirements/Eldin.yaml
> +      East - Goddess Cube near Mogma Turf Entrance: Goddess Sword
These are redundant since just blowing up the rock with the bomb flower ("Nothing") is enough to get to East, so they could be dropped too.

2023-12-24 22:27 UTC, robojumper commented on logic/requirements/Eldin.yaml
> +      Volcano - Goddess Cube near Mogma Turf Entrance: Goddess Sword
I assume you can actually get these in Boko Base, I haven't checked.

2023-12-24 22:27 UTC, robojumper commented on logic/requirements/Lanayru.yaml
> +        End - Blow up Rock on Track: Bomb Bag & Lanayru Mine - Quick Bomb Trick
If I'm understanding this right I think "In Minecart" is also missing an exit to "End" predicated on being able to blow up the rock so that logic actually allows you to leave the minecart into End once the rock is blown up using this trick?

2024-01-05 13:52 UTC, lepelog requested changes

2024-01-05 13:52 UTC, lepelog commented on logic/requirements/Lanayru.yaml
> +        End - Blow up Rock on Track: Bomb Bag & Lanayru Mine - Quick Bomb Trick
Yea, but as long as blowing the rock up from the minecart is not even a trick, it wouldn't change logic at all so it's omitted

2024-01-05 13:52 UTC, lepelog commented on logic/requirements/Eldin.yaml
> +      Volcano Summit - Goddess Cube inside Volcano Summit: Fireshield Earrings
```suggestion
      Volcano Summit - Goddess Cube inside Volcano Summit: Fireshield Earrings & Goddess Sword
```

2024-01-05 13:52 UTC, lepelog commented on logic/requirements/Eldin.yaml
> +      East - Goddess Cube near Mogma Turf Entrance: Goddess Sword
I think they should be removed then

2024-01-07 21:44 UTC, merged