Random Starting Statues
ssrando/ssrando pull request #525
Opened 2024-01-14 05:19 UTC by YourAverageLink

Adds an option to have a random bird statue to start with in each region, rather than the vanilla entrance statues. This excludes the Inside the Volcano and Inside Fire Sanctuary statues, as they would leave the player softlocked.

2024-01-16 17:24 UTC, lepelog requested changes

2024-01-16 17:24 UTC, lepelog commented on gamepatches.py
> +            flag = BIRD_STATUE_FLAGS.get(statue[1], None)
```suggestion
            flag = BIRD_STATUE_FLAGS.get(statue[1])
```
The None is redundant

2024-01-16 17:24 UTC, lepelog commented on changedflags.md
> +35: Sealed Grounds statue checked (in vanilla, this does nothing. Changed to toggle statue for starting statue rando)
Imo this sceneflag was already used by the game for this purpose, just the statue select screen didn't check it, so I think this section can be removed

2024-01-16 17:24 UTC, lepelog commented on patches.yaml
> +    # - 804 # eldin entrance statue - removed, as it is handled by starting statue rando
I think the line can just be removed instead of commented out

2024-01-16 17:24 UTC, lepelog commented on patches.yaml
> +      # - 68 # desert statue checked - removed as it is handled by starting statue rando
same here

2024-01-16 17:24 UTC, lepelog commented on logic/randomize.py
> +            and values["subtype"] == "bird-statue-entrance"
```suggestion
            if values.get("subtype") == "bird-statue-entrance"
```
comparing None is fine

2024-01-16 18:39 UTC, yannl35133 commented on logic/randomize.py
> +            "\Sky\\South East\\Faron Pillar\\First Time Dive"
Don't use these, they are not fixed names. This should be `self.areas.short_to_full(FARON_FIRST_TIME_DIVE)` with `FARON_FIRST_TIME_DIVE = Sky - Faron Pillar - First Time Dive` defined in `constants.py`

2024-01-17 23:53 UTC, yannl35133 approved these changes
lgtm

2024-01-21 14:42 UTC, merged