Restructure Custom Functions
ssrando/ssrando pull request #526
Opened 2024-01-14 16:56 UTC by elijah-thomas774

2024-01-15 15:29 UTC, CovenEsme commented
YES. Finally. I've been meaning to do this for ages. Thanks for taking the time to do this 🏆 

Looks good to me :p

2024-01-16 17:10 UTC, lepelog commented on asm/custom-functions/src/rando/mod.rs
> +    (unsafe { *file_manager::get_ptr() }).anticommit_flag = 1;
```suggestion
    unsafe { (*file_manager::get_ptr()).anticommit_flag = 1 };
```
Otherwise rust just ignores this code, probably because it's UB somehow?

2024-01-16 17:11 UTC, lepelog requested changes
Looks good, found just one instance where the newly generated was different

2024-01-17 16:48 UTC, lepelog commented
Yea, that's a good idea. However, I think that should be done in a separate PR, this is already a huge improvement that I don't want to just sit around for a while

2024-01-17 16:48 UTC, merged