🔔 Academy Bell 🔔
ssrando/ssrando pull request #558
Opened 2024-03-01 16:34 UTC by CovenEsme

## What does this PR do?
Randomizes the item dropped by the Knight Academy bell when it is rung. When the dropped item is collected by the player, Skyloft sceneflag 101 will be set. This flag is checked to make sure that the item cannot be collected multiple times.

## How do you test this changes?
* I tested that ringing the bell drops the randomized item
* I tested that you can ring the bell with a bomb throw (needs the trick enabled to be logically relevant)
* I tested that only one item spawns - even if you hit the bell multiple times
* I tested that hitting the bell, not collecting the item, reloading the area, and then hitting it again still spawns the randomized item
* I tested that hitting the bell, collecting the item, reloading the area, and then hitting it again *does not* spawn the randomized item
* I tested that you can still end the Archery minigame by shooting the academy bell (both if you have collected the item or if you haven't)

## Notes
Shooting the Knight Academy bell during the Archery minigame *cannot* be used to peak the bell item during the minigame. The camera pans away before the item falls out of the bell enough to see it :p

2024-03-01 21:36 UTC, lepelog requested changes

2024-03-01 21:36 UTC, lepelog commented on checks.yaml
> +    - stage/F000/r0/l2/Bell/0xFDE8
There is only one Bell on each layer, right? In those cases I have always omitted the id

2024-03-01 21:51 UTC, CovenEsme commented on checks.yaml
> +    - stage/F000/r0/l2/Bell/0xFDE8
Yeah, there's just the one :p

2024-03-01 21:54 UTC, CovenEsme commented on checks.yaml
> +    - stage/F000/r0/l2/Bell/0xFDE8
Fixed

2024-03-05 21:28 UTC, lepelog requested changes

2024-06-24 09:53 UTC, CovenEsme commented on changedflags.md
> +101: Collected item from Knight Academy Bell
I made this change and tested that the new flag gets used instead of the old :p

2024-07-06 11:17 UTC, lepelog approved these changes

2024-07-06 11:18 UTC, merged